// Code generated by protoc-gen-go.
// source: actions.proto
// DO NOT EDIT!

/*
Package actions is a generated protocol buffer package.

It is generated from these files:
	actions.proto

It has these top-level messages:
	Unit
	Active
	Controls
	Build
	Action
*/
package actions

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Unit struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Unit) Reset()         { *m = Unit{} }
func (m *Unit) String() string { return proto.CompactTextString(m) }
func (*Unit) ProtoMessage()    {}

type Active struct {
	Groups           []int32 `protobuf:"varint,1,rep,name=groups" json:"groups,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Active) Reset()         { *m = Active{} }
func (m *Active) String() string { return proto.CompactTextString(m) }
func (*Active) ProtoMessage()    {}

func (m *Active) GetGroups() []int32 {
	if m != nil {
		return m.Groups
	}
	return nil
}

type Controls struct {
	Brakes           *Unit   `protobuf:"bytes,1,opt,name=brakes" json:"brakes,omitempty"`
	Active           *Active `protobuf:"bytes,2,opt,name=active" json:"active,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Controls) Reset()         { *m = Controls{} }
func (m *Controls) String() string { return proto.CompactTextString(m) }
func (*Controls) ProtoMessage()    {}

func (m *Controls) GetBrakes() *Unit {
	if m != nil {
		return m.Brakes
	}
	return nil
}

func (m *Controls) GetActive() *Active {
	if m != nil {
		return m.Active
	}
	return nil
}

type Build struct {
	Foo              *int32 `protobuf:"varint,1,req,name=foo" json:"foo,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Build) Reset()         { *m = Build{} }
func (m *Build) String() string { return proto.CompactTextString(m) }
func (*Build) ProtoMessage()    {}

func (m *Build) GetFoo() int32 {
	if m != nil && m.Foo != nil {
		return *m.Foo
	}
	return 0
}

type Action struct {
	Controls         *Controls `protobuf:"bytes,1,opt,name=controls" json:"controls,omitempty"`
	Build            *Build    `protobuf:"bytes,2,opt,name=build" json:"build,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *Action) Reset()         { *m = Action{} }
func (m *Action) String() string { return proto.CompactTextString(m) }
func (*Action) ProtoMessage()    {}

func (m *Action) GetControls() *Controls {
	if m != nil {
		return m.Controls
	}
	return nil
}

func (m *Action) GetBuild() *Build {
	if m != nil {
		return m.Build
	}
	return nil
}
