// Code generated by protoc-gen-go.
// source: src/controls.proto
// DO NOT EDIT!

/*
Package controls is a generated protocol buffer package.

It is generated from these files:
	src/controls.proto

It has these top-level messages:
	Unit
	Active
	Controls
*/
package controls

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Unit struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Unit) Reset()         { *m = Unit{} }
func (m *Unit) String() string { return proto.CompactTextString(m) }
func (*Unit) ProtoMessage()    {}

type Active struct {
	Groups           []int32 `protobuf:"varint,1,rep,name=groups" json:"groups,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Active) Reset()         { *m = Active{} }
func (m *Active) String() string { return proto.CompactTextString(m) }
func (*Active) ProtoMessage()    {}

func (m *Active) GetGroups() []int32 {
	if m != nil {
		return m.Groups
	}
	return nil
}

type Controls struct {
	Brakes           *Unit   `protobuf:"bytes,1,opt,name=brakes" json:"brakes,omitempty"`
	Active           *Active `protobuf:"bytes,2,opt,name=active" json:"active,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Controls) Reset()         { *m = Controls{} }
func (m *Controls) String() string { return proto.CompactTextString(m) }
func (*Controls) ProtoMessage()    {}

func (m *Controls) GetBrakes() *Unit {
	if m != nil {
		return m.Brakes
	}
	return nil
}

func (m *Controls) GetActive() *Active {
	if m != nil {
		return m.Active
	}
	return nil
}
