// Code generated by protoc-gen-go.
// source: src/ship.proto
// DO NOT EDIT!

/*
Package ship is a generated protocol buffer package.

It is generated from these files:
	src/ship.proto

It has these top-level messages:
	Vessel
	FuelTank
	Part
*/
package ship

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Vessel struct {
	Width            *float64 `protobuf:"fixed64,1,req,name=width" json:"width,omitempty"`
	Length           *float64 `protobuf:"fixed64,2,req,name=length" json:"length,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Vessel) Reset()         { *m = Vessel{} }
func (m *Vessel) String() string { return proto.CompactTextString(m) }
func (*Vessel) ProtoMessage()    {}

func (m *Vessel) GetWidth() float64 {
	if m != nil && m.Width != nil {
		return *m.Width
	}
	return 0
}

func (m *Vessel) GetLength() float64 {
	if m != nil && m.Length != nil {
		return *m.Length
	}
	return 0
}

type FuelTank struct {
	Radius           *float64 `protobuf:"fixed64,1,req,name=radius" json:"radius,omitempty"`
	Length           *float64 `protobuf:"fixed64,2,req,name=length" json:"length,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *FuelTank) Reset()         { *m = FuelTank{} }
func (m *FuelTank) String() string { return proto.CompactTextString(m) }
func (*FuelTank) ProtoMessage()    {}

func (m *FuelTank) GetRadius() float64 {
	if m != nil && m.Radius != nil {
		return *m.Radius
	}
	return 0
}

func (m *FuelTank) GetLength() float64 {
	if m != nil && m.Length != nil {
		return *m.Length
	}
	return 0
}

type Part struct {
	Vessel           *Vessel   `protobuf:"bytes,1,opt,name=vessel" json:"vessel,omitempty"`
	FuelTank         *FuelTank `protobuf:"bytes,2,opt,name=fuelTank" json:"fuelTank,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *Part) Reset()         { *m = Part{} }
func (m *Part) String() string { return proto.CompactTextString(m) }
func (*Part) ProtoMessage()    {}

func (m *Part) GetVessel() *Vessel {
	if m != nil {
		return m.Vessel
	}
	return nil
}

func (m *Part) GetFuelTank() *FuelTank {
	if m != nil {
		return m.FuelTank
	}
	return nil
}
